### ISSUE TITLE
Add cloud function to populate default categories

### ISSUE THREAD

**Issue by igor-krupenja** [igor-krupenja/zaino#493]
- [ ] maybe put it inside some deploy yarn script?
- [ ] should add `isDefault` for tops
- [ ] also consider the same for demo data
