### ISSUE TITLE
Create deployment scripts

### ISSUE THREAD

**Issue by igor-krupenja** [igor-krupenja/zaino#537]
### shared

- [x] Remove demo-data script completely
- [x] Remove CSV
- [x] Move output to cloud-functions
- [x] Remove other unused files.
- [x] Clean pacakge.json

### cloud-fn

- [x] consider renaming to Firestore
- [x] Investigate if can get rid of .firebaserc — at least rename to use full words.
- [x] Reduce number of npm scripts by getting rid of pre- scripts etc.
- [x] Fix seed data and related function to get categories properly
- [ ] Test PubSub publish
- [x] Update README
- [x] Create deploy section in README
- [x] Update Start in README

### www

- [x] images
- [x] set gloud project https://stackoverflow.com/questions/46770900/how-to-change-the-project-in-gcp-using-cli-commands Use `REACT_APP_FIREBASE_PROJECT_ID`
- [x] placeholder images
