### ISSUE TITLE
Set up debugger

### ISSUE THREAD

**Issue by igor-krupenja** [igor-krupenja/zaino#548]
- [x] **test in monorepo**
- [x] **check unit tests**
- [x] classes to SVGs
- [x] shared
- [x] favicon
- [x] $gcp-storage-url in SCSS
- [x] refactor index and app
- [x] SCSS warnings on compile
- [x] package name and details
- [x] nodemon
- [x] too many scss files in console browser
- [x] stuff in index.html
- [x] clean up .env files
- [x] add nvmrc file
