### ISSUE TITLE
Adopt per-package configs

### ISSUE THREAD

**Issue by igor-krupenja** [igor-krupenja/zaino#570]
- [x] ESLint + Prettier + other stuff from root https://create-react-app.dev/docs/setting-up-your-editor/
- [x] nvmrc in shared
- [x] check .vscode configs
- [x] .gitignore
- [x] restore hosting deploy script
- [x] eslint rule for fn return type
