### ISSUE TITLE
Transition project to TS

### ISSUE THREAD

**Issue by IgorKrupenja** [igor-krupenja/zaino#71]
### Tasks
- [x] remove Babel dependencies
- [x] remove Babel config
- [x] some types could be moved to dev dependencies?
- [x] components
- [x] Slices
- [x] Firebase
- [x] routers
- [x] store
- [x] tests
- [x] test TS source maps in prod
- [x] remove JS rules from ESLint config
- [x] remove JS config
- [x] remove JS support from TS config when all is done
- [x] get rid of requires in Webpack config
- [x] `allowSyntheticDefaultImports`?
- [x] https://webpack.js.org/configuration/configuration-languages/#typescript

### Info

- [x] **important** https://www.typescriptlang.org/docs/handbook/interfaces.html#function-types
- [x] https://www.typescriptlang.org/docs/handbook/jsx.html
- [x] https://redux-toolkit.js.org/usage/usage-with-typescript
- [x] https://medium.com/swlh/convert-your-javascript-react-app-to-typescript-the-easy-guide-631592dc1876
- [x] https://www.sitepoint.com/how-to-migrate-a-react-app-to-typescript/
- [x] https://github.com/microsoft/TypeScript-React-Conversion-Guide
- [x] https://stackoverflow.com/questions/44133420/what-is-the-typescript-return-type-of-a-react-stateless-component
- [x] https://stackoverflow.com/questions/37233735/typescript-interfaces-vs-types
- [x] https://fettblog.eu/typescript-react/getting-started/
